version: '3.10.1'
services:
  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:postgresql://database:5432/db_01_shevtsov -user=postgres -password=133451 -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=133451
      - POSTGRES_DB=db_01_shevtsov
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - database
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "133451"
      POSTGRES_DB: "db_01_shevtsov"
      POSTGRES_HOST: "5432"